//------------------------------------------------------------------------
// Copyright(c) 2023 Ares Mutemet.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Multitapper.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Multitapper VST3 (64Bit)"
#else
#define stringFileDescription	"Multitapper VST3"
#endif
#define stringCompanyName		"Ares Mutemet\0"
#define stringLegalCopyright	"Copyright(c) 2023 Ares Mutemet."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
